### ISSUE TITLE
slackbuild

### ISSUE THREAD

**Issue by sasongko26** [bgli/kbbi-qt#101]
Untuk pemasangan di Slackware dan turunannya dapat menggunakan [slackbuild](https://github.com/sasongko26/kbbi-qt-slackbuild)

**Comment by rafeyu** [comment]
Terima kasih pak @sasongko26, siap dipasang di readme dan dokumentasi :grin: 

Edit:
Untuk memastikan, instalasinya cukup begini kan pak Sasongko?

```
# chmod +x kbbi-qt.SlackBuild
# ./kbbi-qt.SlackBuild
```

**Comment by suciptoid** [comment]
Mantab jiwa pak @sasongko26 + @rafeyu

**Comment by sasongko26** [comment]
Terima kasih pak @rafeyu + @showcheap , Pak @rafeyu instalasinya tidak perlu ditulis pengguna slackware insya Allah sudah mengerti, tapi barangkali ada yang baru bermigrasi ke slackware ditulis juga tidak apa-apa.

instalasi lengkapnya 
`$ git clone https://github.com/sasongko26/kbbi-qt-slackbuild.git`
`$ cd kbbi-qt-slackbuild`
`# chmod +x kbbi-qt.SlackBuild`
`# ./kbbi-qt.SlackBuild`
`# installpkg /tmp/kbbi-qt*.tgz`

**Comment by rafeyu** [comment]
Terima kasih pak @sasongko26, siap eksekusi biar dokumentasinya rame :grin:

**Comment by sasongko26** [comment]
Ya, terima kasih kembali. Silahkan saja, dengan senang hati pak @rafeyu 😁

**Comment by suciptoid** [comment]
Close as #102
