### ISSUE TITLE
Shortcutkey Menubar

### ISSUE THREAD

**Issue by andriawan** [bgli/kbbi-qt#105]
Saya coba tambahkan shorcutkey pada menubar karena ketika saya coba terapkan kombinasi key ( Alt + huruf tertentu) tidak berfungsi atau belum terintegrasi. tambahan shortcut key sudah saya layangkan sebagai commit pada branch dev.

**Comment by suciptoid** [comment]
@andriawan Terimakasih pak @andriawan, nanti saya merge. 🤓
