### ISSUE TITLE
[Feature Request] Pencarian otomatis sebagai standar pencarian KBBI Qt

### ISSUE THREAD

**Issue by alunux** [bgli/kbbi-qt#110]
Seperti yang kita tahu bahwa KBBI Qt memiliki fitur opsional yang dapat diaktifkan untuk melakukan pencarian otomatis (langsung melakukan sorting pada hasil pencarian dan menampilkan hasilnya) dengan mencentang "Aktifkan pencarian otomatis".

Dibandingkan dengan melukakan enter setelah memasukkan kata kunci pada kotak pencarian, saya rasa fitur pencarian otomatis dapat diaktifkan secara default pada KBBI Qt, berhubung hasil pencariannya juga sama dan saya tidak terlalu merasakan penurunan performa pada KBBI Qt.

Mungkin teman-teman pengembang KBBI Qt bisa mempertimbangkan proposal kecil saya ini. Terima kasih.

**Comment by suciptoid** [comment]
Kemarin pernah bandingkan kalau pencarian otmatis performanya sedikit lamban, karena memang belum pakai threading untuk proses pencarianya. Mungkin sebelum menjadikanya sebagai default, harus melakukan hal berikut ini
- Mengubah search engine ke thread lain (Multi thread) agar tidak memblok render UI
- Melakukan delay pencarian sampai user selesai mengetik kata kunci

**Comment by refeed** [comment]
Nah iya, kalau di js ada yang namanya async, entah kalo di Qt ada apa nggak. BTW mungkin bisa tambahin caching juga, biar setiap search nggak harus nyocokin kata di semua kamus.

**Comment by suciptoid** [comment]
@refeed di Qt bisa pakai QThread.

**Comment by suciptoid** [comment]
mantap pak @saa7go
