### ISSUE TITLE
kbbi-qt bisa berjalan di atas HAIKU

### ISSUE THREAD

**Issue by mazbrili** [bgli/kbbi-qt#126]
Hallo semua..
KBBI-Qt bisa berjalan di atas system operasi  [HAIKU](https://www.haiku-os.org/)
diharapkan segera akan muncul di repository software haiku
silahkan untuk mengupdate readme bahwa aplikasi ini bisa jalan di atas haiku
![image](https://user-images.githubusercontent.com/25004583/82279607-2bbb9500-99b7-11ea-8f1e-9b1b1dc1e410.png)

terima kasih

**Comment by suciptoid** [comment]
Terimakasih @mazbrili atas informasinya 😃

**Comment by mazbrili** [comment]
> Terimakasih @mazbrili atas informasinya 😃

sama-sama... silahkan mengunjungi laman project.. siapa tahu berminat mencicipi.. karena haiku sebentar lagi akan release Beta2

**Comment by mazbrili** [comment]
KBBI sudah muncul di software depot haiku..

![image](https://user-images.githubusercontent.com/25004583/87616004-3f2c7780-c73e-11ea-9ca5-df7030f6b83d.png)

tiket ini saya tutup.. maksih semua

**Comment by suciptoid** [comment]
Terimakasih @mazbrili sudah membuat packagenya di HAIKU OS
