### ISSUE TITLE
Filter Query

### ISSUE THREAD

**Issue by azispratama92** [bgli/kbbi-qt#18]
Sabtu, 29 Oktober kemarin, hasil diskusi bareng-bareng bersama Bang Billy & Bu Reamina, menghasilkan beberapa usulan, satu diantaranya adalah tentang "filter query" pada search result KBBI

https://youtu.be/NYSPahOlQDM

**Comment by suciptoid** [comment]
Sip, secara defaultnya emang gak nyampur sama detail sih. tapi kemarin aku pikir biar dapet lebih banyak pencarianya.

Oke nanti coba di pisah, atau di beri opsi mau ikut cari dari detail atau tidak berupa checkbox. 👍

**Comment by azispratama92** [comment]
Ada droplist gitu ya Kang, boleh2

**Comment by suciptoid** [comment]
Pakai checkbox pak, monggo di check kembali, sudah saya tambahkan checkboxnya
