### ISSUE TITLE
Zoom in & out option pada mainwindow.ui --> Horizontal layout --> detailResult

### ISSUE THREAD

**Issue by azispratama92** [bgli/kbbi-qt#19]
Kang, bagaimana caranya supaya window "detailResult" text nya bisa di zoom in & zoom out, bagian manakah yang harus diedit?

Jadi mirip pada fitur scroll zoom pada Libre Office, etc. 

![pemilihan_024](https://cloud.githubusercontent.com/assets/17444955/19843352/37b4f966-9f54-11e6-88c4-57ad5e86bc8d.png)

**Comment by suciptoid** [comment]
Untuk memperbesar / kecil fonta nya ya?

Bisa ditambahi widget slider 

Pseudo
slider (signal) = value change -> detailresult (slot) -> resize font

**Comment by suciptoid** [comment]
Ref1: https://youtu.be/sKi7oArCqUI?t=3m33s
Ref2: https://www.youtube.com/watch?v=B9KVJO1Kjkk&list=PLG7hWxpJRYC-lNJDUwVJmoKh2m5KnWVp2&index=7

**Comment by suciptoid** [comment]
Pak @azispratama92 bisa pegang ini?

**Comment by azispratama92** [comment]
Dicoba dulu nggih, mohon bimbingannya :)

**Comment by suciptoid** [comment]
@azispratama92 sip mantab 👍

**Comment by azispratama92** [comment]
clone terakhir ternyata sudah ada fitur nya XD hohohoho Siapa hayo yg ngoding ?

**Comment by suciptoid** [comment]
@azispratama92 dimana pak? belum ada kayaknya

**Comment by saa7go** [comment]
setahuku QTextEdit bisa zoom in/out text pakai ctrl + scroll wheel (up/down) gitu deh

**Comment by suciptoid** [comment]
Oh, default nya sudah ada yak malahan

**Comment by saa7go** [comment]
diclose aja gimana om?

**Comment by suciptoid** [comment]
Okey 👍
