### ISSUE TITLE
Dokumentasi berjalan

### ISSUE THREAD

**Issue by rafeyu** [bgli/kbbi-qt#20]
Penulisan dokumentasi sedang berjalan, mengikuti perkembangan proyek.

Untuk saat ini kerangkanya seperti ini,

```
1. Pengenalan KBBI-qt
  1.1 Apa itu KBBI-qt
  1.2 Keuntungan pakai KBBI-qt
2. Pemasangan KBBI-qt
  2.1 Di Fedora
  2.2 Di Ubuntu
  2.3 Di distro X
  2.x Instal dari source code
3. Pengenalan antar muka
4. Penggunaan KBBI-qt
5. Solusi masalah, misal kalau ada masalah di distro tertentu, bukan bug (opsional)
```

Saya belum tahu mau dijadikan apa, antara PDF saja atau dokumentasi.md+PDF.

Yang penting jalan dulu, siap terima usulan .. 😘

**Comment by suciptoid** [comment]
Sip pak, lanjutkan @rafeyu 💃 
Markdown biar bisa dibaca langsung di github
PDF sekalian biar bisa diunduh / di masukkan kedalam aplikasi.

**Comment by aliterm** [comment]
kalo mau dokumentasi di GitBook aja kan markdown tuh, dan bisa diunduh dalam format PDF, Epub juga. 😄

**Comment by suciptoid** [comment]
Nah mantab jugak tuh gitbook. Atau sementara ditulis di `.md` repo sini dulu aja pak. di folder `doc` nanti kalau sudah selesai baru deh di taruh di gitbook

**Comment by rafeyu** [comment]
Ok pak, nanti saya taruh di `doc` dulu. Kalau sudah selesai, terus pakai gitbook 😃

**Comment by azispratama92** [comment]
nyumbang versi QT saya (Jadul dari Repo Debian Jessie)

![about qt creator_033](https://cloud.githubusercontent.com/assets/17444955/19878804/9360362e-a01f-11e6-83d9-77943bdede25.png)

**Comment by suciptoid** [comment]
ada update #54 tombol carinya hilang 😬

**Comment by saa7go** [comment]
setelah kucek, tombolnya emang sengaja disembunyikan @raniaamina

**Comment by suciptoid** [comment]
@saa7go iya emang di hilangin kemarin bersamaan dengan fitur auto cari. 😬 makanya senggol pak dokumentasi.

**Comment by suciptoid** [comment]
@showcheap test reply

**Comment by rafeyu** [comment]
Done pak :smile:

**Comment by suciptoid** [comment]
Ditutup aja ya pak @rafeyu 👍

**Comment by rafeyu** [comment]
Siap pak
