### ISSUE TITLE
Error running on Qt Creator 4.0.1

### ISSUE THREAD

**Issue by raniaamina** [bgli/kbbi-qt#22]
Ketika hendak dijalankan dengan Qt Creator 4.0.1 selalu mengalami galat dengat keterangan berikut:
![mainwindow cpp master - kbbi-qt - qt creator_010](https://cloud.githubusercontent.com/assets/22146607/19854320/f11bbb50-9fa0-11e6-93c7-df430c06c912.png)

/home/rania/kbbi-qt/src/mainwindow.cpp:134: error: 'activated' is a protected member of 'QAbstractItemView'
        emit ui->listView->activated(firstRow);
                           ^
/usr/include/qt4/QtGui/qabstractitemview.h:265: declared protected here
    void activated(const QModelIndex &index);
         ^

**Comment by suciptoid** [comment]
PR pak @saa7go #23

**Comment by suciptoid** [comment]
@raniaamina tolong di konfrimasi apakah sudah terselesaikan setelah update dari PR #23 ?
