### ISSUE TITLE
Dialog About / Tentang

### ISSUE THREAD

**Issue by suciptoid** [bgli/kbbi-qt#24]
Sudah ada menunya, belum ada dialognya

**Comment by suciptoid** [comment]
Ada yang mau bikin? Gampang banget ini 😋

**Comment by raniaamina** [comment]
sudah dibuat :-)
![kbbi qt](https://cloud.githubusercontent.com/assets/22146607/19865274/1b77ed92-9fce-11e6-9e4c-d71ce064f423.png)

**Comment by suciptoid** [comment]
mantab @raniaamina

**Comment by azispratama92** [comment]
Wah, otodidak Bu @raniamina keren :+1:

**Comment by suciptoid** [comment]
![photo72082823132063952](https://cloud.githubusercontent.com/assets/1310895/19922198/302db6b2-a114-11e6-939d-daa9629e82d1.jpg)
Pengajuan desain, bu @raniaamina mau ambil?

**Comment by raniaamina** [comment]
Saya pelajari dulu :-)

Pada tanggal 2 Nov 2016 15.51, "Sucipto" notifications@github.com menulis:

**Comment by suciptoid** [comment]
Lanjutkan @raniaamina 👍

**Comment by raniaamina** [comment]
Sudah dikerjakan! :-)
![workspace 1_023](https://cloud.githubusercontent.com/assets/22146607/19959001/e742545e-a1d5-11e6-837f-2971e2027bce.png)

**Comment by suciptoid** [comment]
istimewah

**Comment by suciptoid** [comment]
PR #36
