### ISSUE TITLE
Dialog Bantuan

### ISSUE THREAD

**Issue by suciptoid** [bgli/kbbi-qt#25]
Di menu sudah ada, belum di bikin dialognya.

Isinya juga belum di fikirkan.

**Comment by suciptoid** [comment]
Mungkin bisa digabung #20

**Comment by raniaamina** [comment]
Kalau menurut saya sih kurang fungsional keberadaanya, mungkin dapat disatukan di form tentang biar lebih ringkas. Kontributor-kontributornya juga boleh dimasukkan, bila dirasa dapat menarik minat rekan-rekan lain untuk untuk ikut berkontribusi. Dibuat seperti model about-nya inkscape.

**Comment by suciptoid** [comment]
Oke gabung #24 aja kali yak
