### ISSUE TITLE
Warna fonta hasil query 

### ISSUE THREAD

**Issue by azispratama92** [bgli/kbbi-qt#28]
Kang untuk mengubah warna font hasil pencarian kata, kode yang harus dimodifikasi bagian mana ya ? 

![kbbi](https://cloud.githubusercontent.com/assets/17444955/19878676/6204313a-a01e-11e6-82bc-f2793d78fdf6.png)

Semisal warna hitam dirubah warna biru, atau hijau barangkali text akan lebih mudah dibaca, 

![kamus besar bahasa indonesia_032](https://cloud.githubusercontent.com/assets/17444955/19878712/b926f6fa-a01e-11e6-9b2a-435a211628c2.png)

hehehe, matur nuwun sebelumnya, :)

**Comment by suciptoid** [comment]
Bisa menggunakan funsgi `replace`
di database sudah menggunakan kode html. jadi tinggal replace untuk `<b>` menjadi `<b style="color: green">` misalkan. 😁

**Comment by azispratama92** [comment]
Jadi file *.sqlite database nya nggak di utak-atik Kan Pak? Wokee, Cool :)

**Comment by suciptoid** [comment]
@azispratama92 iya pak bisa 👍

**Comment by saa7go** [comment]
kalau pakai stylesheet aja bisa atau enggak ya? belum pernah nyobain sendiri.  http://doc.qt.io/qt-5/qtextdocument.html#defaultStyleSheet-prop

**Comment by suciptoid** [comment]
kayaknya sih bisa pakai css selector

```
b {
    color: green;
}
```

Sel, 1 Nov 2016 pukul 15.58 Christian Kurniawan notifications@github.com
menulis:

**Comment by suciptoid** [comment]
Done by #32
