### ISSUE TITLE
Database KBBI Terupdate

### ISSUE THREAD

**Issue by suciptoid** [bgli/kbbi-qt#3]
- [ ] Database [KBBI Offline yang sudah ada](https://code.google.com/archive/p/kbbi-offline/) (Versi Windows) masih dalam format DAT sehingga "Saat ini" masih belum bisa diolah.
- [ ] [Database yang masih format CSV](https://github.com/bgli/kbbi) hasil OCR masih belum matang, harus di edit dan di teliti secara manual
- [x] Database versi SQLite

**Comment by raniaamina** [comment]
mungkin perlu bagi-bagi jatah untuk meneliti, supaya lebih cepat.

**Comment by raniaamina** [comment]
Ini yang hendak dijadikan database KBBI versi berapa?

**Comment by suciptoid** [comment]
Kalau ada yang bernah ngoding app di windows, siapa tahu bisa convert file DAT minimal jadi CSV dulu 💃

**Comment by aliterm** [comment]
@showcheap Ngoding apa dulu nih? saya pernah ngoding di Windows 😄

**Comment by suciptoid** [comment]
@aliterm Kalau lihat di [source ini](https://code.google.com/archive/p/kbbi-offline/source/default/source) kira kira pakai apa um? Delphi kayaknya? CMIIW.

Nah sistem yang di pake file DAT di source itu belum mudeng sayanya.

Kalau dulu pernah ambil database gKamus (Indonesia Inggris) emang pakai plain text, dan mudah di konversi ke CSV. Kalau DAT belum pernah aku, siapa tau cuman file sqlite yang di rename extensinya aja, tapi kemarin aku buka palai sqlite juga gak bisa haha.

**Comment by aliterm** [comment]
@showcheap hahaha sekilas liat iya Delphi ada file .pas nya,  tapi klo beneran Delphi harusnya di buat pake Lazarus juga bisa, nanti malem dah ane cobain, siapa tau bisa di convert ke Lazarus wkwkwk

Ane pernah mainan Delphi masalahnya 🙉

**Comment by suciptoid** [comment]
Sip @aliterm aku malah belum pernah coba delphi, baru bisa install doank 😬

**Comment by rafeyu** [comment]
Ini dia pernyataan om Ivan Lanin seputar KBBI V[1].

1: https://twitter.com/ivanlanin/status/791283454319013888

**Comment by suciptoid** [comment]
Aplikasinya multiplatform enggak ya? 
Walaupun aplikasi resminya udah ada dan bisa multi platform, diusahakan project ini tetep di selesaikan. 💃

**Comment by rafeyu** [comment]
@showcheap Skeptis itu perlu, jadi menurut saya itu gak multiplatform.

+1 buat nerusin proyek ini ;)

Apalagi kalau basis data nya bisa dibongkar, lumayan kita bisa dapet KBBI V :D

**Comment by aliterm** [comment]
Ambil aja kata-kata yg gak ada wwkkwkw 🙈 kaya kata direktori, di KBBI v3 gak ada, adanya di v4 🙈

**Comment by suciptoid** [comment]
Sip awesome @aliterm @rafeyu 👯

**Comment by raniaamina** [comment]
Wah ketinggalan jauh saya.
Boleh tuh, tapi mungkin optimis skeptis juga perlu dicoba.

**Comment by suciptoid** [comment]
Oke masalah database sementara di anggep fix dulu yak. Kan udah dapet versi yang SQLite. Untuk kedepan kalau ada yang mengolah database terbaru bisa jadi update untuk aplikasinya. 😁

**Comment by raniaamina** [comment]
SIAP!
