### ISSUE TITLE
Hightlight lema / kata kunci pencarian

### ISSUE THREAD

**Issue by suciptoid** [bgli/kbbi-qt#33]
Lema / kata kunci ditandai dengan hightlight/sorot pada bagian detail

**Comment by suciptoid** [comment]
Memungkinkan gak pak @saa7go ?

**Comment by saa7go** [comment]
ada screenshot contohnya?

**Comment by suciptoid** [comment]
https://youtu.be/-A5S9ka5H9A?t=3m54s

Gak terlalu kelihatan sih kalau yang di video itu, kayake gak pake css.
