### ISSUE TITLE
Pemaketan

### ISSUE THREAD

**Issue by suciptoid** [bgli/kbbi-qt#4]
- [x] Pemaketan ke sistem `deb`

- [x] Pemaketan ke sistem `rpm`

**Comment by suciptoid** [comment]
Mungkin pak @alunux bisa bantu di pemaketan rpm 😄

**Comment by alunux** [comment]
@showcheap Affirmative.

**Comment by alunux** [comment]
Mungkin kita butuh ikon untuk launchernya ya :)

**Comment by alunux** [comment]
@showcheap webhook-nya belum diaktifkan?

**Comment by suciptoid** [comment]
sudah pak, apa belum ter triger?

**Comment by suciptoid** [comment]
<img width="811" alt="screen shot 2016-11-01 at 10 53 29" src="https://cloud.githubusercontent.com/assets/1310895/19879037/7db7bcb4-a021-11e6-9dd9-b0fb67590d20.png">

**Comment by alunux** [comment]
Aha, sorry, tautan di Copr-nya masih mengarah ke git saya. Sip, udah diarahkan ke repo ini. Maaf, kesalahan saya, hehehe.

**Comment by suciptoid** [comment]
@alunux  SIp pak 👍

**Comment by suciptoid** [comment]
kang @baddwin sepertinya pernah maketin `*.deb` juga  😁

**Comment by baddwin** [comment]
Iya, ada beberapa project Qt di Launchpad yang bisa autobuild DEB di sana. Tapi sayangnya sekarang posisi saya tidak pakai Ubuntu. :sweat_smile:

**Comment by alunux** [comment]
@showcheap mungkin bisa diperbarui status issue nya, om.

**Comment by suciptoid** [comment]
@alunux gimana pak?

**Comment by alunux** [comment]
@showcheap pemaketan DEB dan RPM telah selesai, om. Itu loh om, yang ada centang-centangnya.

**Comment by suciptoid** [comment]
yang deb belum tuntas pak 😬

**Comment by alunux** [comment]
@showcheap owalah, kirain udah, hehe.

**Comment by baddwin** [comment]
Kok belum pak @showcheap? Kayaknya kan dah ada yang contrib? Apa perlu dibuat autobuild di Launchpad?

**Comment by suciptoid** [comment]
iya ada kemarin, salah branch tapi.

**Comment by antosamalona** [comment]
Wah, harusnya push ke branch yg mana? Kirain cuman satu branchnya Pak @showcheap
