### ISSUE TITLE
Ubah penamaan MyDialog menjadi lebih spesifik

### ISSUE THREAD

**Issue by saa7go** [bgli/kbbi-qt#41]
Sepertinya nama class MyDialog tidak menjelaskan apa maksud dari fungsi class tersebut.
Mungkin lebih baik diganti menjadi TentangDialog, AboutDialog atau lainnya yang sesuai.

**Comment by suciptoid** [comment]
@raniaamina bisa eksekusi?

**Comment by raniaamina** [comment]
sudah di PR, apakah masih konflik?

**Comment by suciptoid** [comment]
@raniaamina masih pak.

**Comment by suciptoid** [comment]
Sudah beres
