### ISSUE TITLE
Bug saat run via Qt Creator

### ISSUE THREAD

**Issue by rafeyu** [bgli/kbbi-qt#60]
Repo lokal sudah sesuai branch dev. Saat dirun dengan Qt Creator gagal, muncul:

    /home/ramdzi/Project/kbbi-qt/src/mainwindow.cpp:-1:` In member function 'void MainWindow::on_checkAutoCari_clicked()':
    
    /home/ramdzi/Project/kbbi-qt/src/mainwindow.cpp:247: error: 'class Ui::MainWindow' has no member named 'checkAutoCari'
     autoCari = ui->checkAutoCari->isChecked();
                    ^
    
    :-1: error: [Makefile:390: mainwindow.o] Error 1

**Comment by suciptoid** [comment]
Coba pada menu Qt Creator pilih Build > Clean Project "KBBI-Qt"

**Comment by rafeyu** [comment]
Sudah Clean Project, terus run, build all, rebuild all, sama saja
- Btw, jelek banget mau ngelapor hasil galat, malah jadi jempol turun 😅

**Comment by suciptoid** [comment]
Di tempat saya baik baik saja.

Ralat: Coba update commit 547a32a79cedbbe9ff7963a6c137ed02304b290f pak

**Comment by suciptoid** [comment]
soalnya itu sudah gak ada sejak PR dari pak @saa7go

**Comment by rafeyu** [comment]
Masih sama pak. Sebelum pull sore tadi masih lancar, pasca pull malah gini. Sebentar pak saya utak-utik dulu

**Comment by saa7go** [comment]
kalau clone ulang gmn om?

**Comment by rafeyu** [comment]
@saa7go Iya pak, baru saja kepikiran saya. Clone ulang sukses, kayaknya emang trouble di repo lokal saya 😅

Saya close ya pak
