### ISSUE TITLE
Readme.md belum update

### ISSUE THREAD

**Issue by suciptoid** [bgli/kbbi-qt#73]
- [x] Screenshot belum sesuai dengan aplikasi terbaru

- [x] Belum ada cara install dari source (compile)

- [x] Belum ada cara install untuk `*.deb`

- [x] Bagian Contributor belum ada isinya

**Comment by raniaamina** [comment]
wew, siap kerjakan!

**Comment by alunux** [comment]
Oh iya, sekalian sunting bagian versi Fedora yang didukung.

**Comment by raniaamina** [comment]
Fedora yang sudah didukung versi berapa saja ya?

**Comment by suciptoid** [comment]
@raniaamina 23/24/25/Rawhide
