### ISSUE TITLE
[Pemaketan][RPM] Pembaruan Berkas SPEC

### ISSUE THREAD

**Issue by alunux** [bgli/kbbi-qt#85]
Berhubung banyaknya perubahan yang terjadi pada project KBBI Qt dan perubahan ini menyebabkan gagalnya daily build pada Fedora Copr, maka akan dilakukan pembaruan berkas `SPEC` untuk pemaketan RPM. Untuk waktu pengerjaannya masih belum ditentukan.

**Comment by suciptoid** [comment]
Iya kang @alunux , berhubung saya masih belum mudeng utak atik berkas SPEC nya, saya serahkan ke kang @alunux  saja 👍

**Comment by suciptoid** [comment]
Gabung #86
