### ISSUE TITLE
Pemaketan Untuk Versi Rilis

### ISSUE THREAD

**Issue by suciptoid** [bgli/kbbi-qt#86]
Pemaketan final untuk versi rilis

- [x] Windows

- [x] GNU/Linux Deb Family

- [x] GNU/Linux Rpm Family #85 

- [x] Arch Linux

**Comment by suciptoid** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pemaketan](https://trello.com/c/YLubK3IE/1-pemaketan)

**Comment by showcheap** [comment]
tes

**Comment by suciptoid** [comment]
Thanks @alunux 👍

**Comment by suciptoid** [comment]
Oh ya, untuk yang RPM apa sudah pakai db path terbaru kang @alunux ?
https://github.com/bgli/kbbi-qt/blob/dev/src/main.cpp#L31-L36

Di OS Linux masuk kesini
```cpp
dbPath = "/usr/share/KBBI-Qt/data/" + DB_NAME;
```

**Comment by alunux** [comment]
Sudah, kang @showcheap. Sayangnya saya tidak memakai fitur `make install`, saya instal manual. Semua path ikutin aturan mainnya si `KBBI-Qt.pro`, kecuali path ikon.

**Comment by suciptoid** [comment]
@alunux Oke kang 👍

**Comment by suciptoid** [comment]
Di copr kok masih error kang?

**Comment by alunux** [comment]
@showcheap repo Copr pakai branch master, bukan dev.

**Comment by suciptoid** [comment]
Saya chek build terakhir 
https://copr.fedorainfracloud.org/coprs/alunux/kbbi-qt-git/build/480519/
- 2016-11-23 09:51 UTC (28 hours ago)
Sedangkan Branch master latest commit nya
- 17 Nov 2016

Apa mungkin karena webhooknya branch dev ikutan mentriger ulang buildnya yak?

**Comment by alunux** [comment]
Iya kayaknya.

**Comment by raniaamina** [comment]
Yang untuk windows  bukankah sudah dibuat pak @saa7go?

**Comment by suciptoid** [comment]
@raniaamina noted.

**Comment by suciptoid** [comment]
Case closed.
